import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // opsional
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "pisangku",
  description: "Generated by Ananda Salwa pratama",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  antialiased bg-white`}>
        <Header />
        <main className="w-full h-screen max-w-340.5 px-3.75 mx-auto border border-black">
          {/* Main Content */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
