import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import FlowbiteProvider from "@/components/provider/FlowbiteProvider";
import "./globals.css";
// Components
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import RectangleTransition from "@/components/transition/RectangleTransition";
import PageTransition from "@/components/transition/PageTransition";
import { Ubuntu } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // opsional
  variable: "--font-poppins",
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
  display: "swap",
});

export const metadata: Metadata = {
  title: "pisangku",
  description: "Generated by Ananda Salwa pratama",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable}  antialiased bg-white`}>
        {/* Provider */}
        <FlowbiteProvider />
        <RectangleTransition />
        <PageTransition>
          <Header />
          <main className="w-full  px-8 lg:px-[125px] h-fit max-w-340.5  mx-auto mt-10">
            {/* Main Content */}
            {children}
          </main>
          <Footer />
        </PageTransition>
      </body>
    </html>
  );
}
